baseURL = "https://thecenter.netlify.app/"
languageCode = "en-us"
title = "The Center For IRS Help"


[module]

[[module.imports]]
path = "github.com/saderra/hugo-modules/uitheme"

[[module.imports]]
path = "github.com/saderra/hugo-modules/alpinejs"

[[module.imports]]
path = "github.com/saderra/hugo-modules/turbolinks"

[[module.imports]]
path = "github.com/saderra/hugo-modules/netlifycms"

[[module.imports]]
path = "github.com/saderra/hugo-modules/breadcrumbs"

[[module.imports]]
path = "github.com/saderra/hugo-modules/blogtools"



[build]
writeStats = true


